### ISSUE TITLE
what does by_tool mean?

### ISSUE THREAD

**Issue by summereasy** [curtisjamesholt/Holt-Tools#1]
Great addon! I've tested it and it works well.
But the terminal seems to keep warning me about the "scene" doesn't have a "by_tool" stuff blah blah.
So I did an initial check and it seems that line #352 caused all of those warnings. 
```python
bytool = scene.by_tool
```
I've done some initial search but have no clue what that is. 
Is it some special weapon 🔫 ? :D:D

**Comment by curtisjamesholt** [comment]
Ah yeah, cheers for that, just a copy-paste leftover from the BY-GEN addon.
