### ISSUE TITLE
Emission Adjustment should think about Pricinple BSDF Node Emission Color and Emission Strength.

### ISSUE THREAD

**Issue by Qomolangma888** [curtisjamesholt/Holt-Tools#2]
Someone likes using Emission Color and Emission Strength in Pricinple BSDF node to adjust emission effect, so I think Emission Adjustment should think about Pricinple BSDF Node Emission Color and Emission Strength, but only material's name and emission node, then , I thank you very much!  Very Good Work!

**Comment by curtisjamesholt** [comment]
I agree! I will add that to the next version.
